set(_CATKIN_CURRENT_PACKAGE "QSP-SLAM-Ellipsoidal-Prior")
set(QSP-SLAM-Ellipsoidal-Prior_VERSION "0.0.0")
set(QSP-SLAM-Ellipsoidal-Prior_MAINTAINER "zhjd <zhjd@todo.todo>")
set(QSP-SLAM-Ellipsoidal-Prior_PACKAGE_FORMAT "2")
set(QSP-SLAM-Ellipsoidal-Prior_BUILD_DEPENDS "roscpp" "cmake_modules" "sensor_msgs" "std_msgs" "cv_bridge" "image_transport")
set(QSP-SLAM-Ellipsoidal-Prior_BUILD_EXPORT_DEPENDS "roscpp")
set(QSP-SLAM-Ellipsoidal-Prior_BUILDTOOL_DEPENDS "catkin")
set(QSP-SLAM-Ellipsoidal-Prior_BUILDTOOL_EXPORT_DEPENDS )
set(QSP-SLAM-Ellipsoidal-Prior_EXEC_DEPENDS "roscpp")
set(QSP-SLAM-Ellipsoidal-Prior_RUN_DEPENDS "roscpp")
set(QSP-SLAM-Ellipsoidal-Prior_TEST_DEPENDS )
set(QSP-SLAM-Ellipsoidal-Prior_DOC_DEPENDS )
set(QSP-SLAM-Ellipsoidal-Prior_URL_WEBSITE "")
set(QSP-SLAM-Ellipsoidal-Prior_URL_BUGTRACKER "")
set(QSP-SLAM-Ellipsoidal-Prior_URL_REPOSITORY "")
set(QSP-SLAM-Ellipsoidal-Prior_DEPRECATED "")