set(_CATKIN_CURRENT_PACKAGE "SimDataset")
set(SimDataset_VERSION "0.0.0")
set(SimDataset_MAINTAINER "lj <lj@todo.todo>")
set(SimDataset_PACKAGE_FORMAT "2")
set(SimDataset_BUILD_DEPENDS "gazebo_msgs" "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(SimDataset_BUILD_EXPORT_DEPENDS "gazebo_msgs" "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(SimDataset_BUILDTOOL_DEPENDS "catkin")
set(SimDataset_BUILDTOOL_EXPORT_DEPENDS )
set(SimDataset_EXEC_DEPENDS "gazebo_msgs" "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(SimDataset_RUN_DEPENDS "gazebo_msgs" "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(SimDataset_TEST_DEPENDS )
set(SimDataset_DOC_DEPENDS )
set(SimDataset_URL_WEBSITE "")
set(SimDataset_URL_BUGTRACKER "")
set(SimDataset_URL_REPOSITORY "")
set(SimDataset_DEPRECATED "")